spring:
  mail: 
    host: mail.quinto.site
    port: 25
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    required: true
                    enable: true
    username: desarrollo@quinto.site
    password: Carmelita23    
  datasource:
    url: jdbc:mysql://localhost:3306/upcycling?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout:
        3600s
  port: 8080